param(
    [string]$OutputDir = "$PSScriptRoot\generated"
)

New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null

# These fixtures exercise the non-Excel conversion/trim paths with the same
# sentinel strategy used by the Excel workbooks. Run only on a host with Word
# and PowerPoint installed; the production Excel examples remain generated by
# the artifact-tool builder.
$word = $null
$ppt = $null
try {
    $word = New-Object -ComObject Word.Application
    $word.Visible = $false
    $doc = $word.Documents.Add()
    $section = $doc.Sections.Item(1)
    $section.PageSetup.Orientation = 0 # portrait
    $section.PageSetup.PaperSize = 7 # A4
    $doc.Content.InsertAfter("DOCX EDGE FIXTURE - LEFT_SENTINEL`r`n")
    $doc.Content.InsertAfter("Unicode: Đường biên Ω 一 | wrapped paragraph | RIGHT_SENTINEL`r`n")
    $table = $doc.Tables.Add($doc.Range($doc.Content.End - 1, $doc.Content.End - 1), 121, 12)
    for ($r = 1; $r -le 121; $r++) {
        for ($c = 1; $c -le 12; $c++) {
            $value = if ($r -eq 1) { "HEADER_$c" } elseif ($c -eq 1) { "LEFT_$r" } elseif ($c -eq 12) { "RIGHT_$r" } else { "R${r}C${c}" }
            $table.Cell($r, $c).Range.Text = $value
        }
    }
    $doc.SaveAs2((Join-Path $OutputDir "word_large_table.docx"), 16)
    $doc.Close($false)

    $doc = $word.Documents.Add()
    $doc.Content.InsertAfter("WORD WIDE LANDSCAPE LEFT_SENTINEL`r`n")
    $doc.Sections.Item(1).PageSetup.Orientation = 1 # landscape
    $doc.Sections.Item(1).PageSetup.PaperSize = 5 # Legal
    $doc.Content.InsertAfter(("WIDE_COLUMN " * 80) + " RIGHT_SENTINEL`r`n")
    $doc.SaveAs2((Join-Path $OutputDir "word_wide_legal.docx"), 16)
    $doc.Close($false)

    $ppt = New-Object -ComObject PowerPoint.Application
    $presentation = $ppt.Presentations.Add()
    $slide = $presentation.Slides.Add(1, 12) # blank
    $box = $slide.Shapes.AddTextbox(1, 30, 30, 900, 80)
    $box.TextFrame.TextRange.Text = "PPT EDGE FIXTURE - LEFT_SENTINEL | Unicode Đ Ω 一 | RIGHT_SENTINEL"
    $box.TextFrame.TextRange.Font.Size = 24
    $slide.Shapes.AddTable(24, 12, 30, 140, 900, 430) | Out-Null
    $slide2 = $presentation.Slides.Add(2, 12)
    $shape = $slide2.Shapes.AddShape(1, 20, 20, 3000, 1500)
    $shape.TextFrame.TextRange.Text = "FULL-BLEED / LARGE VECTOR / TRIM GUARD"
    $slide3 = $presentation.Slides.Add(3, 12)
    $slide3.Shapes.AddTextbox(1, 40, 40, 900, 500).TextFrame.TextRange.Text = ("WIDE_CONTENT " * 120)
    $presentation.SaveAs((Join-Path $OutputDir "powerpoint_edge_cases.pptx"), 24)
    $presentation.Close()
} finally {
    if ($word) { $word.Quit() }
    if ($ppt) { $ppt.Quit() }
    [GC]::Collect()
    [GC]::WaitForPendingFinalizers()
}
